### ISSUE TITLE
Licence and building instructions required

### ISSUE THREAD

**Issue by bigbigmdm** [tomek-o/CH341A-tool#3]
I am interested in your repository. But I need a GNU licence to modify or use it. Please add a GPL licence file to this repository.
The readme.MD file does not contain instructions on how to compile and build your project. Please add it. I want to migrate this repository to linux.

**Comment by tomek-o** [comment]
It is supposed to be BSD, license file is now added. There is also some third party code under a mix of BSD, MIT, public domain and Beerware licenses.
I've added compilation instruction (not much as it is basically "open project group in the IDE and hit Build"). As it uses old version of C++ Builder and it is GUI VCL application, I don't think it would be directly portable to Linux though. Wine also won't work as it cannot work with required driver.

**Comment by bigbigmdm** [comment]
Thanks, @tomek-o !

One more question, could you add Polish translation of my program [IMSProg](https://github.com/bigbigmdm/IMSProg)?

**Comment by tomek-o** [comment]
> One more question, could you add Polish translation of my program [IMSProg](https://github.com/bigbigmdm/IMSProg)?

I'm not a fan of translating and translations, especially for "technical" applications.

**Comment by bigbigmdm** [comment]
@tomek-o Ok. Thank you!
